export const DEATH_LINES = [
  "DOWNLOAD THE REAL GAME — oh wait, this IS the real game",
  "Game Over. Unlike other mobile games, we actually mean it.",
  "You died. No loot boxes can save you here.",
  "RETRY? It's free. We know that's suspicious.",
  "Your final score has been reported to the authorities.",
  "GAME OVER. No microtransactions to continue.",
  "In other games, that run would cost $4.99.",
  "Error: player.skill not found",
  "YOU DIED. No $2.99 revive. Just shame.",
  "Your power went to zero. Just like our marketing budget.",
  "Have you tried being better at fake games?",
  "404: Survival not found.",
  "Connection timed out. Your skills have been terminated.",
  "You.exe has stopped responding.",
  "Press F to pay respects. It's still free.",
  "Would you like to save your game? Too bad. We don't do that here.",
  "You died doing what you loved: playing a game from an ad.",
  "GG. No rematch. Well, actually yes rematch. It's free.",
  "FATAL ERROR: fun.exe has stopped responding. Free to restart.",
  "Achievement unlocked: Touch grass.",
  "Run terminated. Unlike IAP, this one's non-refundable.",
  "Your insurance does not cover in-game deaths.",
  "The dial-up modem of your skill has disconnected.",
  "You.jpg is corrupted. Please defrag your talent.",
];

export const MULTIPLY_LINES = [
  "JUST LIKE THE AD PROMISED",
  "Is this even legal?",
  "THE AD WASN'T LYING (for once)",
  "Dopamine deployed ✓",
  "SATISFACTION GUARANTEED*",
  "Number go brrrr",
  "This is not a drill.",
  "Your accountant is crying.",
  "COMBO SECURED. The FTC has entered the chat.",
  "Big number unlocked.",
  "Holy compound interest, Batman.",
  "The algorithm is pleased.",
  "THIS IS PERFECTLY NORMAL",
  "No, seriously, this is how math works.",
];

export const TRAP_LINES = [
  "lol you trusted a mobile ad",
  "THE AD LIED. SHOCKING.",
  "Bamboozled. Hoodwinked.",
  "Trust issues: activated",
  "That's what you get for optimism",
  "The fine print said ÷. You didn't read it.",
  "Fool me once, shame on you. Fool me twice, check the color.",
  "That gold gate had red eyes. You chose to ignore it.",
  "MISLEADING UI: a proud mobile game tradition.",
  "The gate said ×3. Your lawyer is on the phone.",
  "You thought you were multiplying. Lol.",
  "False advertising at its finest. Welcome to the internet.",
  "Classic bait and switch. The industry salutes you.",
];

export const MYSTERY_LINES = [
  "??? resolved.",
  "Chaos engine activated.",
  "Even we didn't know.",
  "RNG has spoken.",
  "The algorithm decided for you.",
  "Slot machine go brr",
];

export const WAVE_LINES = [
  "Wave {n}. Still not a scam.",
  "Wave {n}. No paywall detected.",
  "Wave {n}. The ad continues.",
  "Wave {n} of ∞.",
  "Wave {n}. Still free. Still confused.",
  "Wave {n}. Sponsored by nobody.",
  "Wave {n}. The FTC is watching.",
  "Wave {n}. Your mom is impressed.",
  "Wave {n}. No ads in this ad.",
  "Wave {n}. Still 0 microtransactions.",
  "Wave {n}. AOL has entered the chat.",
  "Wave {n}. We're still not selling your data.",
  "Wave {n}. Difficulty dial turned slightly.",
  "Wave {n}. Have you tried our premium tier? (There isn't one.)",
  "Wave {n}. The programmer apologizes.",
  "Wave {n}. It do be like that.",
  "Wave {n}. Zero in-app purchases. Zip.",
  "Wave {n}. Buffering dignity...",
];

export const POPUP_MESSAGES = [
  { title: "⚠️ VIRUS DETECTED", body: "Your device has 47 viruses.\nAlso you're about to hit a wall.", btn: "OK" },
  { title: "🎉 CONGRATULATIONS!", body: "You are the 1,000,000th player!\nClick to claim your prize!", btn: "CLAIM" },
  { title: "💾 SYSTEM ALERT", body: "DOWNLOADING MORE RAM...\n████████░░ 78%", btn: "Cancel" },
  { title: "🔥 HOT SINGLES", body: "HOT SINGLES IN YOUR LANE\nClick to meet them!", btn: "Meet Now" },
  { title: "⚠️ WARNING", body: "Fun.exe has stopped responding.", btn: "Close" },
  { title: "🛡️ ANTIVIRUS", body: "YOUR ANTIVIRUS HAS A VIRUS.", btn: "Help" },
  { title: "📧 NEW EMAIL", body: "FWD: FWD: FWD: FREE POWER\n(definitely not a scam)", btn: "Open" },
  { title: "💀 MAINFRAME", body: "MAINFRAME BREACHED.\nHackers are stealing your score.", btn: "Panic" },
  { title: "🔧 SYSTEM32", body: "SYSTEM32 DELETED.\nJust kidding. Or are we?", btn: "😰" },
  { title: "📞 MISSED CALL", body: "Your mom called.\nShe reached Wave 12.", btn: "Hang Up" },
  { title: "🤖 CLIPPY", body: "It looks like you're trying\nto survive. Would you like\nhelp with that?", btn: "No" },
  { title: "💜 BONZI BUDDY", body: "Hello! I'm Bonzi!\nLet me help you by\nblocking your screen!", btn: "Please No" },
  { title: "🌐 NETSCAPE NAVIGATOR", body: "This page requires\nAdobe Flash Player.\nPlease update now.", btn: "Install" },
  { title: "🔔 AOL INSTANT MSG", body: "SuRfBoArD99: hey\nare u there??\n(this is an emergency)", btn: "A/S/L?" },
  { title: "💽 LIMEWIRE", body: "Downloading: AdGame\n████████████ 99%\n(it might be a virus btw)", btn: "Cancel" },
  { title: "🖨️ PRINTER ERROR", body: "PC LOAD LETTER\nWhat does that mean?\nNobody knows.", btn: "Okay" },
  { title: "⏰ WINDOWS UPDATE", body: "Restarting in 3...\n2... just kidding.\nBut imagine.", btn: "Not Now" },
  { title: "🔍 ASK JEEVES", body: "Did you mean:\n'how to not die'\nin this game?", btn: "Search" },
  { title: "🎵 REALPLAYER", body: "RealPlayer wants to\nset itself as your\ndefault for everything.", btn: "Why" },
  { title: "⚡ YOU'RE A WINNER!", body: "You have won a\nFREE IPOD NANO!\nClick to claim.", btn: "Decline" },
  { title: "🖥️ MY COMPUTER", body: "You are running low\non virtual memory.\nClose your heart.", btn: "Ignore" },
  { title: "🌟 GEOCITIES", body: "Welcome to my homepage!\nPlease sign my\nguest book! 🌈✨", btn: "Sign It" },
  { title: "🔒 NORTON ANTIVIRUS", body: "SCAN COMPLETE\n4,721 threats found.\n1 of them is this game.", btn: "Quarantine" },
  { title: "📱 RINGTONE OFFER", body: "Get the latest\npolyphonic ringtones!\nOnly $9.99/month", btn: "Block" },
  { title: "🎮 ACHIEVEMENT", body: "Achievement Unlocked:\nPlaying games at work.\nTreatment: classified.", btn: "Worth It" },
];

export const LOADING_MSGS = [
  "THIS IS AN AD.",
  "But like... a real one.",
  "Installing trust issues...",
  "Buffering dopamine...",
  "Deploying pixel punks...",
  "Clearing your cookies...",
  "You've got mail. Just kidding.",
  "PLAY NOW →",
];

export const TUTORIAL_LINES = [
  "← TAP LEFT / RIGHT →",
  "Green = good. Red = bad. Gold = ???",
  "Yes, this actually works.",
  "This is real gameplay. Not a redirect.",
];

export const SYSTEM_RESTORED = [
  "SYSTEM RESTORED",
  "THREAT NEUTRALIZED",
  "POPUP DESTROYED",
  "CONNECTION SECURED",
];
