export const STAGES = [
  {
    id: 'cookies',
    name: 'Cookie Preferences',
    subtitle: 'A tiny banner with normal intentions.',
    joke: 'We use cookies to improve your experience of being tracked.',
    objective: 3,
    seconds: 34,
    corruption: 0.05,
    patterns: ['evasion'],
    maxModals: 1,
    declineLabels: ['Reject All', 'Decline', 'No Thanks'],
    acceptLabels: ['Accept All', 'Allow Cookies'],
    result: 'Preferences saved locally, spiritually ignored.',
  },
  {
    id: 'privacy',
    name: 'Privacy Settings',
    subtitle: 'All toggles are off, except the ones that remember being on.',
    joke: 'Your choices matter. Our defaults matter slightly more.',
    objective: 4,
    seconds: 38,
    corruption: 0.18,
    patterns: ['evasion', 'toggles', 'labelSwap'],
    maxModals: 1,
    declineLabels: ['Save Minimal', 'Reject Partners', 'Privacy Mode'],
    acceptLabels: ['Enable All', 'Personalize Me'],
    result: 'You rejected several partners and gained no new friends.',
  },
  {
    id: 'trial',
    name: 'Free Trial',
    subtitle: 'Seven days free. Cancellation available in a dream.',
    joke: 'No charge today, except the emotional deposit.',
    objective: 4,
    seconds: 36,
    corruption: 0.3,
    patterns: ['evasion', 'labelSwap', 'confirmshame', 'delay'],
    maxModals: 2,
    declineLabels: ['Skip Trial', 'Continue Free', 'Maybe Later'],
    acceptLabels: ['Start Free Trial', 'Add Card'],
    result: 'You escaped the trial before the calendar noticed.',
  },
  {
    id: 'newsletter',
    name: 'Newsletter Hydra',
    subtitle: 'One popup enters. Several popups leave.',
    joke: 'Unsubscribe from updates about unsubscribing.',
    objective: 5,
    seconds: 42,
    corruption: 0.46,
    patterns: ['modalStack', 'hydra', 'confirmshame', 'labelSwap'],
    maxModals: 3,
    declineLabels: ['Unsubscribe', 'No Email', 'Leave Inbox Alone'],
    acceptLabels: ['Keep Me Updated', 'Daily Digest'],
    result: 'Your inbox is technically quieter, pending review.',
  },
  {
    id: 'arbitration',
    name: 'Arbitration Clause',
    subtitle: 'The fine print has developed collision.',
    joke: 'By reading this sentence you waive your right to understand it.',
    objective: 5,
    seconds: 43,
    corruption: 0.62,
    patterns: ['terrain', 'evasion', 'labelSwap', 'delay'],
    maxModals: 3,
    declineLabels: ['Opt Out', 'Preserve Rights', 'Object'],
    acceptLabels: ['Binding Arbitration', 'Agree Forever'],
    result: 'You retained one legal right. It immediately hid.',
  },
  {
    id: 'partners',
    name: 'Partner Consent Network',
    subtitle: 'A small constellation of vendors wants to know you deeply.',
    joke: 'Trusted partners include everyone with a spreadsheet.',
    objective: 6,
    seconds: 46,
    corruption: 0.78,
    patterns: ['vendors', 'toggles', 'modalStack', 'magnet'],
    maxModals: 4,
    declineLabels: ['Reject Vendors', 'Essential Only', 'Close Network'],
    acceptLabels: ['Share With 842 Partners', 'Optimize Revenue'],
    result: 'Eight hundred vendors felt a brief, unfamiliar boundary.',
  },
  {
    id: 'boss',
    name: 'Final Agreement',
    subtitle: 'ACCEPT ALL has stopped pretending to be a button.',
    joke: 'Finalizing preferences. Please do not perceive the machinery.',
    objective: 3,
    seconds: 55,
    corruption: 1,
    patterns: ['boss', 'magnet', 'modalStack', 'labelOverwrite', 'terrain'],
    maxModals: 5,
    boss: true,
    declineLabels: ['Reject Core', 'Deny Consent', 'Close Agreement'],
    acceptLabels: ['ACCEPT ALL'],
    result: 'Preferences saved. The interface looks genuinely surprised.',
  },
];

export const ENDLESS_STAGE = {
  id: 'endless',
  name: 'Auto-Renewal',
  subtitle: 'The agreement updates every month and so do the threats.',
  joke: 'You may cancel any time by completing this forever.',
  objective: Infinity,
  seconds: 9999,
  corruption: 0.86,
  patterns: ['evasion', 'toggles', 'modalStack', 'hydra', 'terrain', 'vendors', 'magnet', 'labelSwap'],
  maxModals: 5,
  declineLabels: ['Cancel Renewal', 'Reject Changes', 'Stay Free'],
  acceptLabels: ['Renew Automatically', 'Accept Updated Terms'],
  result: 'Auto-renewal cancelled until it renews itself.',
};

export function getStage(st) {
  return st.mode === 'endless' ? ENDLESS_STAGE : STAGES[st.stageIndex];
}
